server:
  port: 4990

jwt:
  secret: Key#SuperSecret$Aforo2SS#JavaMicroservices#987654321

# localhost:4990/security/health  -> http://localhost:5001/health
spring:
  application:
    name: appgateway
  cloud:
    gateway:
      routes:
        - id: ms-security
          uri: http://localhost:5001
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1
        - id: ms-account
          uri: http://localhost:5002
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        - id: ms-deposit
          uri: http://localhost:5003
          predicates:
            - Path=/deposit/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        - id: ms-withdrawal
          uri: http://localhost:5004
          predicates:
            - Path=/withdrawal/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        - id: ms-movements
          uri: http://localhost:5005
          predicates:
            - Path=/movements/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

management:
  endpoints:
    web:
      exposure:
        include: "*"
